### ISSUE TITLE
[KYC] Document Validation Step

### ISSUE THREAD

**Issue by migueltrevinom** [Open-Verifik/web-sdk#15]
### Description

The demo demonstrates exactly what we have to replicate in the KYC process where we have two options:

1. uploading the file from your machine
2. openning the camera feed and take a photo on real time but it has to be done manually, we haven't completed the way to do this automatically, the ideal scenario would be to constantly call an API to check if the data is being properly extracted or use a poor OCR system on the frontend just to detect words and the other method of faceapi to detect the biggest face inside the photo

There are several things to consider in this step and we have to display the errors here prior sending the user to the results page.

![Image](https://github.com/Open-Verifik/web-sdk/assets/9138358/2e259f22-fbf4-42e1-8953-9be563849840)

![Image](https://github.com/Open-Verifik/web-sdk/assets/9138358/98a77ea9-a15e-41d0-a14c-57165f910da2)

### TODO

- [x] Validate the document type is supported by the projectFlow
- [x] Validate the Country of the document is supported by the projectFlow
- [x] Validate it has a face
- [x] Validate it has text

**Comment by migueltrevinom** [comment]
Backend completed

Frontend pending 

- [ ] Handle those errors and show the proper translation

**Comment by NicolasHT95** [comment]
**Can't make any test due to the following**

In the UI I put this client in the black list, that means that all other user should be able to make a registration

![Image](https://github.com/Open-Verifik/web-sdk/assets/138807516/1d866052-f330-4e14-bdae-7d09bcebff5a)

But no matter what I do after i finish the form i receive this response



![Image](https://github.com/Open-Verifik/web-sdk/assets/138807516/ec0cedfe-05d8-4464-be9c-4853b536c32d)
